# Generated by Django 2.2.8 on 2019-12-13 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191203_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=254, unique=True, verbose_name='Электронная почта')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки')),
            ],
            options={
                'verbose_name': 'Почтовый адрес на рассылку',
                'verbose_name_plural': 'Почтовые адреса на рассылку',
                'ordering': ['-created'],
            },
        ),
    ]
