# Generated by Django 2.2.10 on 2020-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miet_union', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='secret_key',
            field=models.CharField(default='UNgy5ETjEkNsCaBt0sR7GxoV1ydrSA', max_length=30, verbose_name='Секретный ключ'),
        ),
    ]
