# Generated by Django 2.2.8 on 2019-12-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miet_union', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=250, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('no_info', 'Нет информации'), ('in_progress', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='no_info', max_length=250, verbose_name='Статус')),
                ('rank', models.CharField(choices=[('student', 'Студент'), ('graduate_student', 'Аспирант'), ('worker', 'Сотрудник')], default='no_info', max_length=250, verbose_name='Студент, Аспирант или Сотрудник')),
            ],
            options={
                'verbose_name': 'Материальная помощь',
                'verbose_name_plural': 'Материальная помощь',
                'ordering': ['last_name'],
            },
        ),
    ]
