# Generated by Django 2.2.8 on 2019-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionsOfProfcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Комиссии профкома',
                'verbose_name_plural': 'Комиссии профкома',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HelpForProforg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'В помощь профоргу',
                'verbose_name_plural': 'В помощь профоргу',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HelpForStudentProforg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'В помощь студенческому профоргу',
                'verbose_name_plural': 'В помощь студенческому профоргу',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NormativeDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Законодательные, нормативные и уставные документы',
                'verbose_name_plural': 'Законодательные, нормативные и уставные документы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionOfPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Защита персональных данных',
                'verbose_name_plural': 'Защита персональных данных',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TheMainActivitiesOfProforg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Основные направления деятельности профорга',
                'verbose_name_plural': 'Основные направления деятельности профорга',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Полезные ссылки',
                'verbose_name_plural': 'Полезные ссылки',
                'ordering': ['title'],
            },
        ),
    ]
